name: Build and deploy .NET Core application to Web App MarsWebPacMen
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Run Tests
        working-directory: src
        run: dotnet test MarsRover.sln

      - name: dotnet publish
        working-directory: src/Mars.Web
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
  deploy-to-prod:
    name: Deploy to production
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: 'https://${{ env.WEBAPP_NAME }}.azurewebsites.net/'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
  
      - name: Deploy to production env
        uses: azure/webapps-deploy@v2
        id: deploy-to-production
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          package: .         
